services:
  openproject-recurring-tasks:
    build: .
    image: openproject-recurring-tasks
    container_name: openproject-recurring-tasks
    env_file:
      - path: .env
    volumes:
      - type: bind
        source: ./app
        target: /app