networks:
  default:
    name: skynet
    external: true

services:
  openproject-recurring-tasks:
    build: .
    restart: unless-stopped
    image: openproject-recurring-tasks
    container_name: openproject-recurring-tasks
    env_file: ".env"
    environment:
      TZ: America/Chicago
    volumes:
      - type: bind
        source: ./app
        target: /app