services:
  openproject-automation-scripts:
    build: .
    image: openproject-automation-scripts
    container_name: openproject-automation-scripts
    env_file:
      - path: .env
    volumes:
      - type: bind
        source: ./app
        target: /app